algorithms:
- grid: {}
  name: ItemKNN
  params:
    K: 20
- grid: {}
  name: EASE
  params:
    l2: 20
metrics:
- K: 20
  name: CalibratedRecallK
- K: 10
  name: CalibratedRecallK
optimisation_metric: null
test_data:
  data_in:
    filename: /Users/robinverachtert/workspace/doctorate/recpack/examples/test_pipeline/test_in
  data_out:
    filename: /Users/robinverachtert/workspace/doctorate/recpack/examples/test_pipeline/test_out
train_data:
  filename: /Users/robinverachtert/workspace/doctorate/recpack/examples/test_pipeline/train
validation_data: null
