# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.8.6

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  key: recpackv001
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install .

test:
  stage: test
  needs: []
  script:
    - pytest --cov=recpack recpack/tests/ --cov-config=.coveragerc
    # - python setup.py test
    # - pip install tox flake8 # you can also use tox
    # - tox -e py36,flake8

pages:
  stage: deploy
  needs:
    - test
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd doc
    # Generate the auto generated pages.
    - sphinx-autogen -o source/generated/ source/recpack.algorithms.rst -t source/_templates/
    - sphinx-autogen -o source/generated/ source/recpack.data.rst -t source/_templates/
    - sphinx-autogen -o source/generated/ source/recpack.metrics.rst -t source/_templates/
    - sphinx-autogen -o source/generated/ source/recpack.preprocessing.rst -t source/_templates/
    - sphinx-autogen -o source/generated/ source/recpack.splitters.rst -t source/_templates/
    - sphinx-autogen -o source/generated/ source/recpack.postprocessing.rst -t source/_templates/
    - sphinx-autogen -o source/generated/ source/recpack.pipelines.rst -t source/_templates/
    # Render HTML
    - make html
    # Move the build to public
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - master

publish:pypi:
  stage: deploy
  needs:
    - test
  script:
    - sed "s/<<env.CI_JOB_TOKEN>>/${CI_JOB_TOKEN}/" .pypirc > ~/.pypirc
    - pip install twine
    - python setup.py bdist_wheel
    - python3 -m twine upload --repository gitlab dist/*
  only:
    - tags
