"""

The metric module contains metrics to evaluate performance of recommendations with.
Metrics compare the scores generated by an algorithm to the expected output.

Recpack provides a set of preimplemented algorithms, and the ability to create your own.
All preimplemented metrics only consider the topK recommendations,
since that makes for the most realistic evaluation.

.. currentmodule:: recpack.metrics

.. contents:: Table of Contents
    :depth: 2

Global Metrics
---------------
Global metrics are computed on the whole dataset, 
and do not require any aggregation to get a single value

.. autosummary::
    :toctree: generated/

    CoverageK
    PercentileRanking

Listwise Metrics
----------------
Listwise metrics compute a single score per user,
which are then aggregated over all users to get a single value.

.. autosummary::
    :toctree: generated/

    DCGK
    NDCGK
    RecallK
    CalibratedRecallK
    PrecisionK
    IntraListDiversityK
    ReciprocalRankK

Elementwise Metric
------------------
Elementwise metrics compute a score per recommended item,
which are then aggregated over all recommendations to get a single value.

.. autosummary::
    :toctree: generated/

    HitK
    IPSHitRateK
    WeightedHitK
    DiscountedGainK
"""


from recpack.metrics.coverage import CoverageK
from recpack.metrics.dcg import DCGK, NDCGK
from recpack.metrics.diversity import IntraListDiversityK
from recpack.metrics.hit import HitK, DiscountedGainK, WeightedHitK
from recpack.metrics.ips import IPSHitRateK
from recpack.metrics.precision import PrecisionK
from recpack.metrics.recall import RecallK, CalibratedRecallK
from recpack.metrics.reciprocal_rank import ReciprocalRankK
from recpack.metrics.percentile_ranking import PercentileRanking

# TODO: I would like to change this so it is the actual name,
# rather than a different one
METRICS = {
    "CoverageK": CoverageK,
    "NDCGK": NDCGK,
    "DCGK": DCGK,
    "IntraListDiversityK": IntraListDiversityK,
    "IPSHitRateK": IPSHitRateK,
    "HitK": HitK,
    "WeightedHitK": WeightedHitK,
    "DiscountedGainK": DiscountedGainK,
    "PrecisionK": PrecisionK,
    "RecallK": RecallK,
    "CalibratedRecallK": CalibratedRecallK,
    "ReciprocalRankK": ReciprocalRankK,
    "PercentileRanking": PercentileRanking,
}
