splitter:
  type: TimedSplit
  params:
    t: 1580630400
    t_delta: 7200

evaluator:
  type: TrainingInTestOut

algorithms:
  - type: "popularity"
  - type: "ease"
  - type: "itemKNN"
    params:
      K: 50

metrics:
  - "NDCG"
  - "Recall"

K_values:
  - 5
  - 10
  - 20
  - 100
